export {default as Home} from "./Home";
export {default as PrivacyPolicy} from "./PrivacyPolicy";
export {default as Terms} from "./Terms";
export {default as Disclaimer} from "./Disclaimer";
export {default as LeaderBoard} from "./LeaderBoard";
export {default as Contact} from "./Contact";
export {default as Reward} from "./Reward";
export {default as DeleteAccount} from "./DeleteAccount";
export {default as OpenChallenge} from "./OpenChallenge";